merge: фикс версий и логики
Siberian797/java-filmorate pull request #4
Opened 2023-03-01 21:59 UTC by Siberian797

2023-03-02 05:44 UTC, krylov-sergey-sergeevich requested changes
Привет

1) Важно: а где workflow гитхабовские которые должны были быть по дефолту в ветке? Они должны были бы тесты запустить. Без этого зачесть работу не смогу.
2) Давай в исключения добавим информацию о айди

Буду ждать с правками, без первого пункта трудно проверять функциональность =)

2023-03-02 05:44 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private FilmService filmService;
Можно лучше: private final FilmService filmService; и докинуть аннотацию @requiredargsconstructor

2023-03-02 05:44 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmNotExistException.java
> +        super("There is no such film. Check your input");
А айди фильма не будем указывать, которого нет?

2023-03-02 05:44 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmNotValidException.java
> +        super("This film is invalid. Check your input");
А айди фильма не будем указывать, который некорректный?

2023-03-02 05:44 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/UserNotExistException.java
> +        super("There is no such user. Check your input");
Айди добавить

2023-03-02 05:44 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/UserNotValidException.java
> +        super("This user is invalid. Check your input");
Айди добавить

2023-03-02 05:44 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Можно лучше: Long id;

2023-03-02 05:44 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LocalDate releaseDate;
@NotNull

2023-03-02 05:44 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Positive
Можно еще так: @Min(1)

2023-03-02 05:44 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private int id;
Можно лучше: Long id;

2023-03-02 05:44 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmServiceImpl.java
> +@Service("FilmService")
("FilmService") - это для чего?

2023-03-02 12:05 UTC, Siberian797 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private FilmService filmService;
Не совсем понял

2023-03-03 05:32 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-03-03 06:51 UTC, merged